### ISSUE TITLE
[FR] Sort by artist/year/album?

### ISSUE THREAD

**Issue by xfzv** [mctofu/deadbeef-library#14]
I've been using the plug-in along with [mctofu/musiclib](https://github.com/mctofu/musiclib) for a few hours, so far so good. Thank you so much for sharing.

Is there any way to implement sorting by artist/**year**/album? I tried to modify `libbrowser.c` by adding:

```diff
static const gchar*         BROWSE_BY_ARTIST_ALBUM      = "artist/album";
+ static const gchar*         BROWSE_BY_ARTIST_YEAR_ALBUM = "artist/year/album";

gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (browse_by_box), BROWSE_BY_ARTIST_ALBUM);
+ gtk_combo_box_text_append_text (GTK_COMBO_BOX_TEXT (browse_by_box), BROWSE_BY_ARTIST_YEAR_ALBUM);
```

and re-compiling the plug-in, but unfortunately it doesn't work as expected. It sorts my library by genre/artist/album instead. :disguised_face:

I guess there would have modifications to do with [mctofu/musiclib](https://github.com/mctofu/musiclib) too?

Thanks.

**Comment by mctofu** [comment]
:wave: As you've found, those changes add the new options to the UI but there's additional work needed to support that on the backend. It's not very flexible right now so each sort option needs its own implementation.

Currently to implement a new sort type you'd:
1. Add a new browse option to the UI at the end of the list
2. Update the [grpc protocol](https://github.com/mctofu/musiclib-grpc/blob/72c659a05b20f54816158c722877020f59e5dfca/musiclib.proto#L31-L38) to also include the new option at the end of the list and [regenerate](https://github.com/mctofu/musiclib-grpc/blob/main/protogen.sh) the client/server stubs. It's expected that the order of the browse options in the UI matches the order in the protobuf at the moment 😬. I think that's why you saw a different ordering used.
3. In mctofu/musiclib build a new index by artist/year/album. It'd look like a cross between the [artist/album](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/metadata.go#L185) index and the [year](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/metadata.go#L157) index. It also needs to be wired into the [IndexedLibrary](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/library.go#L163-L178) and the browse type [mapping](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/cmd/server/main.go#L171-L188) needs to be updated.

You could also experiment by changing the behavior of one of the existing sorts to avoid doing all those steps up front.

Those suggested steps end up creating a folder for each year though and unless the artist has many albums per year it'd be a bit cumbersome to navigate. Maybe prefixing the year to the album name would be a better interface?

**Comment by xfzv** [comment]
Thanks for these detailed instructions.

> Those suggested steps end up creating a folder for each year though and **unless the artist has many albums per year it'd be a bit cumbersome to navigate.**

Indeed.

> Maybe prefixing the year to the album name would be a better interface?

Definitely! something like this:
![Untitled](https://user-images.githubusercontent.com/78810647/191500443-4626a33d-98fe-4cb9-8220-7c3dce07721e.png)

Considering I'd only modify an existing sorting type, I thought I could skip steps 1 and 2. I tried to merge the [artist/album](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/metadata.go#L185-L192) and [year](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/metadata.go#L157-L165) functions as described in step 3 to include the year before the album name.

I tried both:

```go
func NewArtistAlbumIndex() *MetadataIndex {
	return NewMetadataIndex(
		[]NodeBuilder{
                        artistNodeBuilder("modartist"),
                        albumNodeBuilder("modalbum"),
			artistNodeBuilder("artist"),
			albumNodeBuilder("artistalbum"),
			songNode,
		})
}
```

and

```go
func NewArtistAlbumIndex() *MetadataIndex {
	return NewMetadataIndex(
		[]NodeBuilder{
			artistNodeBuilder("modartist","artist"),
			albumNodeBuilder("modalbum","artistalbum"),
			songNode,
		})
}
```

but I'm getting the following errors when trying to compile the server binary:

```sh
❯ go build -o musiclib-grpc-server ./cmd/server
# github.com/mctofu/musiclib
./metadata.go:12:6: NodeBuilder redeclared in this block
	./metadata copy.go:12:6: other declaration of NodeBuilder
./metadata.go:14:6: MetadataIndex redeclared in this block
	./metadata copy.go:14:6: other declaration of MetadataIndex
./metadata.go:20:6: NewMetadataIndex redeclared in this block
	./metadata copy.go:20:6: other declaration of NewMetadataIndex
./metadata.go:78:6: sortChildren redeclared in this block
	./metadata copy.go:78:6: other declaration of sortChildren
./metadata.go:91:6: NewGenreIndex redeclared in this block
	./metadata copy.go:91:6: other declaration of NewGenreIndex
./metadata.go:101:6: genreNode redeclared in this block
	./metadata copy.go:101:6: other declaration of genreNode
./metadata.go:116:6: NewModifiedAtIndex redeclared in this block
	./metadata copy.go:116:6: other declaration of NewModifiedAtIndex
./metadata.go:127:6: modifiedYearNode redeclared in this block
	./metadata copy.go:127:6: other declaration of modifiedYearNode
./metadata.go:142:6: modifiedMonthNode redeclared in this block
	./metadata copy.go:142:6: other declaration of modifiedMonthNode
./metadata.go:157:6: NewYearIndex redeclared in this block
	./metadata copy.go:157:6: other declaration of NewYearIndex
./metadata.go:157:6: too many errors
```

**Comment by mctofu** [comment]
For the "year - album name" approach the quickest way to try it out would be to edit the [`albumNodeBuilder`](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/metadata.go#L211-L227) function to also grab the [album year](https://github.com/mctofu/musiclib/blob/40d61b3cbab7497a2c791af20a816547198ceef2/metadata.go#L168-L171) and then prefix it to the album name. You won't need to update `NewArtistAlbumIndex` with that approach.
